In [1]:
#Q1 Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np

arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [3]:
#Q2 Accept two lists of 5 elements each from the user.Convert them to numpy arrays.
#Concatenate these arrays and print it. Also sort these arrays and print it.

In [28]:
import numpy as np

lst1=[]
lst2=[]
for i in range(0,5):
    item1=int(input())
    item2=int(input())
    lst1.append(item1)
    lst2.append(item2)
print("list 1 is : ",lst1)
print("list 2 is : ",lst2)

arr1=np.array(lst1)
arr2=np.array(lst2)
print("array 1 is",arr1)
print("array 2 is",arr2)

print("sorted array 1 is : ",np.sort(arr1))
print("sorted array 2 is : ",np.sort(arr2))

conarr=np.concatenate([arr1,arr2])
print("concatenated array : ",conarr)
print("sorted concatenated array is : ",np.sort(conarr))

23
90
67
53
12
19
76
45
33
65
list 1 is :  [23, 67, 12, 76, 33]
list 2 is :  [90, 53, 19, 45, 65]
array 1 is [23 67 12 76 33]
array 2 is [90 53 19 45 65]
sorted array 1 is :  [12 23 33 67 76]
sorted array 2 is :  [19 45 53 65 90]
concatenated array :  [23 67 12 76 33 90 53 19 45 65]
sorted concatenated array is :  [12 19 23 33 45 53 65 67 76 90]


In [6]:
#Q3 Write a code snippet to find the dimensions of a ndarray and it's size.

In [13]:
import numpy as np

arr=np.array([[45,67,90],[12,34,87]])
print(arr)
print("dimensions of array : ",arr.ndim)
print("size of he array : ",arr.size)

[[45 67 90]
 [12 34 87]]
dimensions of array :  2
size of he array :  6


In [14]:
#Q4 How to convert a 1D array into a 2D array ?

In [27]:
import numpy as np
a=np.array([23,15,45,78,43,29,51,70])
print(a)
print("shape of the array : ",a.shape)
a2=a[np.newaxis,:]
print(a2)
print("using new axis function : ",a2.shape)
a3=np.expand_dims(a,axis=1)
print(a3)
print("using expand_dims function : ",a3.shape)

[23 15 45 78 43 29 51 70]
shape of the array :  (8,)
[[23 15 45 78 43 29 51 70]]
using new axis function :  (1, 8)
[[23]
 [15]
 [45]
 [78]
 [43]
 [29]
 [51]
 [70]]
using expand_dims function :  (8, 1)


In [29]:
# Q5 Consider two square numpy arrays. Stack them vertically and horizontally.

In [33]:
import numpy as np
a=np.array([[66,14],[54,29]])
b=np.array([[31,83],[10,78]])
print("first array is : ",a)
print("second array is : ",b)
print("horizontally stack : ",np.hstack((a,b)))
print("vertically stack : ",np.vstack((a,b)))

first array is :  [[66 14]
 [54 29]]
second array is :  [[31 83]
 [10 78]]
horizontally stack :  [[66 14 31 83]
 [54 29 10 78]]
vertically stack :  [[66 14]
 [54 29]
 [31 83]
 [10 78]]


In [34]:
# Q6 How to get unique items and counts of unique items ? 

In [38]:
import numpy as np
arr=np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,16,16])
print("given array : ",arr)
u,count=np.unique(arr,return_counts=True)
print("unique items in array : ",u)
print("unique items count : ",count)

given array :  [11 11 12 13 14 15 16 17 12 13 11 14 18 16 16]
unique items in array :  [11 12 13 14 15 16 17 18]
unique items count :  [3 2 2 2 1 3 1 1]
